### ISSUE TITLE
Stem link not working for some colours.

### ISSUE THREAD

**Issue by Tamihere** [Tamihere/book-project#2]
colour stem links not working, can not seem to figure it out.

Here is the link to show an example. 
[file:///Users/toka/Projects/Tamihere/book-project/index.html](url)

And here is another link for Each index.
[https://github.com/Tamihere/book-project](url)

The only link working is the purple stem link. I think the problem comes from placement of whats in front but I can not seem to figure it out.

Thanks in advance.

**Comment by sehsarah** [comment]
Can close this issue now that it's been addressed :)
