### ISSUE TITLE
issue with stem links and background images.

### ISSUE THREAD

**Issue by Tamihere** [Tamihere/book-project#4]
when resizing the page or using a device to load my site, the stem korus branch off of the stems. And the same happens with the theme backgrounds.

Here are a few examples.
![Screen Shot 2019-10-15 at 10 47 55 AM](https://user-images.githubusercontent.com/43526563/66785313-63ea8900-ef39-11e9-8507-79a3db4cc28f.png)
![Screen Shot 2019-10-15 at 10 48 21 AM](https://user-images.githubusercontent.com/43526563/66785347-7c5aa380-ef39-11e9-9218-c3f1d820d3f7.png)
![Screen Shot 2019-10-15 at 10 48 09 AM](https://user-images.githubusercontent.com/43526563/66785350-7d8bd080-ef39-11e9-9a5a-65a36f272059.png)

Thanks in advance.

**Comment by sehsarah** [comment]
Is this fixed now @Tamihere ? Then it can be closed
